### ISSUE TITLE
Template feedback

### ISSUE THREAD

**Issue by brody192** [nxfi777/SurrealDB-Railway#1]
Hello! Thank you for your template submission, I have some suggestions to improve the template.
- Deploy from a [docker image](https://hub.docker.com/r/surrealdb/surrealdb) instead of a repo.
- Use the officially recognized prefix for all database-related variables `DB_`. example: `DB_USER`.
- Use [template functions](https://docs.railway.app/guides/create#template-variable-functions) for the username and password variables.

If you need any help please open a help thread on our [discord server](https://discord.gg/railway) because I'd love to help you make this template the best it can be!

**Comment by nxfi777** [comment]
@brody192 Done. However, I tried out the template functions and they are not working.

<img width="346" alt="template functions test" src="https://github.com/nxfi777/SurrealDB-Railway/assets/127808926/e3c8e086-444a-4aba-8624-9450fbb34dc7">


The image above shows the config I used (I also tried the Base64 version). It does not generate the string before creating the environment on deploy.

**Comment by brody192** [comment]
for some reason double quotes are needed for the char string.
I don't know if thats the string you wanted to use, but I would recommend using this string for passwords that could show up in URLs
`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_!~*`

**Comment by brody192** [comment]
You are publishing your own image for surreal? any reason why you aren't using the official image I linked above?

**Comment by nxfi777** [comment]
The reason I've built my own image is because there are certain configurations that requires the SurrealDB CLI and to my knowledge Railway only supports a custom start command. I've also ran into some binary issues with SurrealDB and this seems to be the best way to get a lot of customisability on Railway. If you are able to deploy a working environment with custom start options as seen in the `start.sh` file in this [repo](https://github.com/nxfi777/SurrealDB-Railway/blob/main/start.sh) with the just default image, by all means...

If Railway supported Docker Compose, this would be a much easier process.

**Comment by nxfi777** [comment]
I've just found out that changing the environment variables is not possible because SurrealDB does not handle root user changes. For example, I tried modifying `DB_PASS` and I could no longer connect to the database... This is most likely a SurrealDB issue, not a Railway issue
